In [1]:
"""
Title: PageRank algo
contributed by <`williamchangTW`>
"""
import numpy as np
from scipy.sparse import csc_matrix
from scipy.linalg import norm
import time 
start = time.time()
#determine the size of adj
def File_max(path):
    A=list()
    fp = open(path, "r")
    for line in iter(fp):
        line1=line.strip().split(",")
        for i in range(len(line1)):
            if int(line1[i]) not in A:
                A.append( int(line1[i]) )      
    fp.close()
    return max(A)

#change txt file to adjacency matrix type=np.array
def FiletoAD(path):
    size=File_max(path)
    A=np.zeros((size,size))
    fp = open(path, "r")
    for line in iter(fp):
        line1=line.strip().split(",")
        A[int(line1[0])-1][int(line1[1])-1]=1
    fp.close()
    return A    

def pageRank(G, s = .85, maxerr = .01):
    """
    Computes the pagerank for each of the n states
    Parameters
    ----------
    G: matrix representing state transitions
       Gij is a binary value representing a transition from state i to j.
    s: probability of following a transition. 1-s probability of teleporting
       to another state.
    maxerr: if the sum of pageranks between iterations is bellow this we will
            have converged.
    """
    n = G.shape[0]

    # transform G into markov matrix A
    A = csc_matrix(G,dtype=np.float)
    #calcualate outdegree of vertex x
    rsums = np.array(A.sum(1))[:,0]
    print("rs",rsums)
    ri, ci = A.nonzero()
    A.data /= rsums[ri]
    print(A)

    # bool array of sink states
    sink = rsums==0

    # Compute pagerank r until we converge
    ro, r = np.zeros(n), np.ones(n)

    while np.sum(np.abs(r-ro)) > maxerr:
        ro = r.copy()
        # calculate each pagerank at a time
        for i in range(0,n):
            # inlinks of state i
            Ai = np.array(A[:,i].todense())[:,0]
            # account for sink states
            Di = sink / float(n)
            # account for teleportation to state i
            Ei = np.ones(n) / float(n)

            r[i] = ro.dot( Ai*s + Di*s + Ei*(1-s) )
            #print(r)
    print(type(r))
    # return normalized pagerank
    return r/np.linalg.norm(r)

if __name__=='__main__':
    path='hw3dataset/graph_2.txt'
    G=FiletoAD(path)
    print(G)
    k= pageRank(G,s=.86)
    print('a',k)
    end = time.time()
    elapsed = end - start
    print("Time taken: ", elapsed, "seconds.")

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
rs [1. 1. 1. 1. 1.]
  (4, 0)	1.0
  (0, 1)	1.0
  (1, 2)	1.0
  (2, 3)	1.0
  (3, 4)	1.0
<class 'numpy.ndarray'>
a [0.4472136 0.4472136 0.4472136 0.4472136 0.4472136]
Time taken:  0.002988100051879883 seconds.
