In [4]:
'''
Title: PageRank
contributed by <'williamchangTW'>
'''
import time 
import numpy as np
from scipy.sparse import csc_matrix
from scipy.linalg import norm
start = time.time()

#determine the size of adj
def File_max(path):
    A=list()
    fp = open(path, "r")
    for line in iter(fp):
        line1=line.strip().split(",")
        for i in range(len(line1)):
            if int(line1[i]) not in A:
                A.append( int(line1[i]) )      
    fp.close()
    return max(A)

   
def FiletoAD(path):
    size=File_max(path)
    A=np.zeros((size,size))
    fp = open(path, "r")
    for line in iter(fp):
        line1=line.strip().split(",")
        A[int(line1[0])-1][int(line1[1])-1]=1
    fp.close()
    return A    

def pageRank(G, s = .85, maxerr = .05):
    """
    Computes the pagerank for each of the n states
    Parameters
    ----------
    G: matrix representing state transitions
       Gij is a binary value representing a transition from state i to j.
    s: probability of following a transition. 1-s probability of teleporting
       to another state.
    maxerr: if the sum of pageranks between iterations is bellow this we will
            have converged.
    """
    n = G.shape[0]

    # transform G into markov matrix A
    A = csc_matrix(G,dtype=np.float)
    rsums = np.array(A.sum(1))[:,0]#calcualate outdegree of vertex x
    print("rs",rsums)
    ri, ci = A.nonzero()
    A.data /= rsums[ri]
    print(A)

    # bool array of sink states
    sink = rsums==0
    # Compute pagerank r until we converge
    ro, r = np.zeros(n), np.ones(n)
    interation=1

    while np.sum(np.abs(r-ro)) > maxerr:
        print(interation)
        print(np.sum(np.abs(r-ro)))
        ro = r.copy()
        # calculate each pagerank at a time
        for i in range(0,n):
            # inlinks of state i
            Ai = np.array(A[:,i].todense())[:,0]
           
            # account for sink states
            Di = sink / float(n)
        
            #By definition of Quick reference 
            r[i] = ro.dot( Ai*s + Di*(1-s) )#+ Ei*(1-s) )
        interation+=1
    # return normalized pagerank
    return r/np.linalg.norm(r)

if __name__=='__main__':
    path='hw3dataset/graph_6.txt'
    G=FiletoAD(path)
    print(G)
    k= pageRank(G,s=.85)
    print('a',k)
    end = time.time()
    elapsed = end - start
    print("Time taken: ", elapsed, "seconds.")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
rs [26.  0.  0. ...  0. 24.  0.]
  (58, 1)	0.038461538461538464
  (834, 1)	0.038461538461538464
  (283, 2)	0.038461538461538464
  (1057, 3)	0.038461538461538464
  (202, 4)	0.038461538461538464
  (0, 5)	0.038461538461538464
  (35, 5)	0.038461538461538464
  (330, 5)	0.038461538461538464
  (360, 5)	0.038461538461538464
  (386, 5)	0.038461538461538464
  (420, 5)	0.038461538461538464
  (647, 5)	0.038461538461538464
  (688, 5)	0.038461538461538464
  (1057, 5)	0.038461538461538464
  (1133, 5)	0.038461538461538464
  (1162, 5)	0.038461538461538464
  (179, 6)	0.038461538461538464
  (1120, 6)	0.038461538461538464
  (78, 7)	0.038461538461538464
  (904, 7)	0.038461538461538464
  (381, 8)	0.038461538461538464
  (385, 8)	0.038461538461538464
  (539, 8)	0.038461538461538464
  (661, 8)	0.038461538461538464
  (929, 8)	0.038461538461538464
  :	:
  (31